### ISSUE TITLE
Import DataLoader not supporting in torch version 1.0.0

### ISSUE THREAD

**Issue by sanjailal** [DAI-Lab/SteganoGAN#53]
* SteganoGAN version or git commit:
* Python version : 3.6.9
* Pip version :  19.3.1
* PyTorch version : 1.0.0
* Operating System: Google Colab

### Description

Was trying to run basic_fit.ipynb in Google Colab.

Got an error in this statement
```from steganogan.loader import DataLoader```

when I changed my torch version to 1.4.0 the error disappears but kernel is dead when i run 
```steganogan.decode('output.png')```
and no success message for 
```steganogan.encode('input.png', 'output.png', 'This is a super secret message!')```

Got these errors

ImportError
 from torch.jit.annotations import Optional
ImportError: cannot import name 'Optional'

**Comment by pvk-developer** [comment]
Hello @sanjailal ,

This kind of issues are not part of `SteganoGAN`, however, in order to use Google Colab for your fitting or running your experiments, I will suggest you to do the following:

- First install `steganogan` and other "requierements" that have been capped #54 (as we have not made a release yet, you should install it with the following command (1st code cell): `!pip install Pillow==6.2.2 torchvision==0.2.1 torch==1.0.0 steganogan `
- Second, you will need the training data uploaded or downloaded in the google colab. You can achieve so by uploading your data folder or running the following script (2nd code cell):
```
%%shell

# Div2K
# -------------------------
mkdir data
cd data
mkdir div2k
cd div2k

wget http://data.vision.ee.ethz.ch/cvl/DIV2K/DIV2K_valid_HR.zip
mkdir val
unzip -j DIV2K_valid_HR.zip -d val/_
rm DIV2K_valid_HR.zip

wget http://data.vision.ee.ethz.ch/cvl/DIV2K/DIV2K_train_HR.zip
mkdir train
unzip -j DIV2K_train_HR.zip -d train/_
rm DIV2K_train_HR.zip
``` 
Then run the rest of the `basic_fit.ipynb` and also, be aware that **10 epochs** are not enought, so do **100 epochs instead**. ` steganogan.fit(train, validation, epochs=100)`

After the model is fitted you can then encode and decode: 
```
steganogan.encode('input.jpg', 'output.png', 'This is a super secret message!')
steganogan.decode('output.png')
```
